### ISSUE TITLE
Failed Example 

### ISSUE THREAD

**Issue by MNapoli1970** [Helios06/sms_gateway#19]
Hi,

While I was installing sms_gateway on **HA (Raspberry Pi5 8Gb)**, I set up MQTT to reflect your example.
In HA, MQTT messages are well published and consumed. On the other hand, sms_gateway does provide me with the following stack trace:
```
11/14/2024 05:03:00 PM MQTT send message received
Traceback (most recent call last):
  File "/sms_manager.py", line 162, in <module>
    main()
  File "/sms_manager.py", line 155, in main
    main_modem(log_level, options)
  File "/sms_manager.py", line 77, in main_modem
    mqtt_client.loop_forever()
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 2297, in loop_forever
    rc = self._loop(timeout)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 1686, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 2100, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 3142, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 3808, in _packet_handle
    return self._handle_publish()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 4145, in _handle_publish
    self._handle_on_message(message)
  File "/usr/lib/python3.12/site-packages/paho/mqtt/client.py", line 4501, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/sms_manager.py", line 57, in on_message
    logging.info(f"... %s", message["txt"])
                            ~~~~~~~^^^^^^^
TypeError: string indices must be integers, not 'str'

```

Forget about the issue...
I did not understood the test instructions in a proper way.

**Comment by Helios06** [comment]
I am back in HA,
I will then study all problems since 2024 and after many HA updates it's not working any more
Give me time
